---
- name: add gluster repo
  yum:
    name: centos-release-gluster
    state: present

- name: install gluster client
  yum:
    name:
      - glusterfs
      - glusterfs-fuse
    state: present

- name: create gluster mount dir
  file:
    name: /var/gluster
    state: directory

- name: mount gluster shared storage
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "glnode1:/gv0"
    fstype: glusterfs
    opts: "defaults,_netdev,backupvolfile-server=glnode2"
    state: mounted

