---
- name: add gluster repo
  yum:
    name: centos-release-gluster
    state: present

- name: install GlusterFS
  yum:
    name: glusterfs-server
    state: present

- name: start glusterd
  systemd:
    name: glusterd
    state: started
    enabled: yes
