---
- name: Rsyslog config to send alerts
  blockinfile:
    path: /etc/rsyslog.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK: enable remote logging"
    content: |
      # ### begin forwarding rule ###
      *.=warning @192.168.10.250:514
      # ### end of the forwarding rule ###

- name: Rsyslog restart
  systemd:
    name: rsyslog
    state: restarted


